file=$1
sed -i 's/HNRNPKL/HNRNPK/g' $file
sed -i 's/RORBL/RORB/g' $file
sed -i 's/SPIN1L/SPIN1/g' $file
sed -i 's/CZH18ORF25/C18orf25/g' $file
sed -i 's/RPL17-C18orf32/C18orf32/g' $file
sed -i 's/APH1AL/APH1A/g' $file
sed -i 's/AVDL/AVD/g' $file
sed -i 's/LMAN1L/LMAN1/g' $file
sed -i 's/CREB3L4/CREB3/g' $file
sed -i 's/2-Mar/MARCH2/g' $file
sed -i 's/MARCHF2/MARCH2/g' $file
sed -i 's/CHD1Z/CHD1W/g' $file
sed -i 's/CHD1/CHD1W/g' $file
sed -i 's/CHD1WW/CHD1W/g' $file
sed -i 's/ATP5F1AZ/ATP5F1AW/g' $file
sed -i 's/ATP5F1A/ATP5F1AW/g' $file
sed -i 's/ATP5F1AWW/ATP5F1AW/g' $file
sed -i 's/CREB3L3/CREB3/g' $file
sed -i 's/orf/ORF/g' $file
sed -i 's/RFKL/RFK/g' $file
